# Generated by Django 4.2 on 2023-04-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_producto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Product',
        ),
    ]
