# Generated by Django 4.2 on 2023-04-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dni',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
